"""The site's master device-code list.

Extracted from ``Ashraf/Medical Devices CODE.doc`` on the archive drive — 171
codes, against the 64 that have cell maps in ``device_config``. It is the
authority for what a code *is*, and says nothing about where the fields sit on
the form; the two are independent and both are needed.

Committed as data rather than read at run time, deliberately. The source is a
legacy .doc on an external drive and parsing it needs Word through COM, so
reading it live would tie the tool to one machine with one drive attached.

To regenerate, with the drive mounted and Word installed, open the document and
read table 1 — column 3 is the device name, column 4 a template filename of the
form ``000-XX000-0000`` whose middle token is the code. Skip row 1, the header.

**Codes missing from this list are not necessarily wrong.** ``GP`` (Holter) has
a working cell map and real files behind it; the document simply does not list
it. ``SK`` appears on 326 archive files and is genuinely unidentified.
"""

#: Code -> device name, exactly as the master document records it. Some entries
#: are Arabic; they are kept verbatim rather than transliterated, because that
#: is what an engineer reading a register will recognise.
DEVICE_NAMES: dict[str, str] = {
    "AA":    "Anesthesia",
    "AB":    "Vaporizers",
    "AC":    "Defibrillator",
    "AD":    "Pacemaker",
    "AE":    "Diathermy,Cryo",
    "AF":    "ECG",
    "AGH":   "Patient Monitor (ECG, SPO2)",
    "AH":    "Pulse Oximeter",
    "AI":    "Infusion Pump",
    "AJ":    "Suction",
    "AK":    "Baby Incubator",
    "AL":    "Phototherapy",
    "AM":    "Ventilator",
    "AN":    "Thermometer,ambient",
    "AO":    "Thermometer , patient",
    "AP":    "Blood Pressure meter",
    "AQ":    "Water Bath",
    "AR":    "Blood Electrolyte / Electrolyte Analyzer",
    "AS":    "Centrifuge",
    "AT":    "Cell Counter",
    "AU":    "Chemistry Analyzer",
    "AV":    "Elisa Reader",
    "AW":    "Electrophoresis",
    "AX":    "Lab Incubator",
    "AY":    "Virus & PCR Analyzer",
    "AZ":    "Auto Analyzer",
    "BA":    "Densitometer",
    "BS":    "Ca00l Balance",
    "BT":    "Prothrombin Timer",
    "BU":    "Cell Separator",
    "BQ":    "Flatbed Platelet Agitator",
    "BV":    "Blood Gas (ABG)",
    "BB":    "Utrasound,Abdomen",
    "BC":    "Ultrasound ,Eye",
    "BD":    "X-Ray ,Mammography",
    "BE":    "X-Ray, Mobile",
    "BF":    "X-Ray, Conventional",
    "BW":    "CT",
    "BX":    "MRI",
    "BG":    "جهاز قياس ضغط العين",
    "BH":    "فحص قاع العين",
    "BI":    "جهاز تصوير الشبكية بصبغة الفلورسين و تحليل الصورة بالكمبيوتر",
    "BJ":    "Auto Refractometer",
    "BK":    "Nerve Stimulator",
    "BL":    "Autoclave",
    "BM":    "Hemodialysis",
    "BN":    "Therapeutic Ultrasound",
    "BR":    "Audiometer",
    "BO":    "Ph Meter",
    "BP":    "Balance",
    "BY":    "Muscle Stimulator",
    "BZ":    "Syringe",
    "CA":    "Dental x-Ray",
    "CB":    "Digital Blood Pressure",
    "AGCB":  "Patient monitor (NIBP)",
    "CC":    "Cautry",
    "CD":    "Endoscopic Set",
    "CE":    "Mercury Meter",
    "CF":    "Baby Warmer",
    "CG":    "Thermometer",
    "CH":    "Blood analyzer",
    "CI":    "Short Wave",
    "CJ":    "Pulse rotor",
    "CK":    "Infrared lamb",
    "CL":    "Myography",
    "CM":    "Laser pointer",
    "CN":    "Microwave",
    "CO":    "Knee stretcher",
    "CP":    "Vertebral column stretcher",
    "CQ":    "Wax device",
    "CR":    "C.P.M",
    "CS":    "Trade mill",
    "CT":    "Laser level system",
    "CU":    "Magnetic level system",
    "CV":    "Spectrophotometer",
    "CW":    "Laboratory microscope",
    "CX":    "Vortex",
    "CY":    "Slide dryer",
    "CZ":    "Mixture device",
    "DA":    "shaker",
    "DB":    "Hot plate",
    "DC":    "Incinerator",
    "DD":    "P.T",
    "DE":    "Colony counter",
    "DF":    "Baby bal",
    "DG":    "C.B.C Analyzer",
    "DH":    "ENDO-ILLUMINATION",
    "DI":    "Measuring of urination rate device.",
    "DJ":    "Csogaval Keratometer",
    "DK":    "Visual field testing device",
    "DL":    "Thermal sealing machine",
    "DM":    "Optical Filler Device",
    "DN":    "Amplaid clinical audiometer device",
    "DO":    "Oxygen Concentrator",
    "DP":    "Unit revealed nose and ear",
    "DQ":    "Ear pressure measuring device",
    "DR":    "Nerve Stimulator",
    "DS":    "Spirometer",
    "DT":    "جهاز تحليل البولينا بالدم",
    "DU":    "IMMUNE ASSAY",
    "DV":    "Light source",
    "DW":    "HEATER AIR MATTRESS",
    "DX":    "جهاز نبض جنين",
    "DY":    "Blood Warmer",
    "DZ":    "جهاز قياس سكر تراكمي Accumulative glucose meter",
    "EA":    "C-arm",
    "EB":    "Vibrator",
    "EC":    "Laminar flow",
    "ED":    "Heart lung machine",
    "EE":    "Flow meter",
    "EF":    "جهاز حشو ضوئي",
    "EG":    "جهاز لغسيل الالات",
    "EH":    "جهاز تحميض أوتوماتيك",
    "EJ":    "جهاز خلط بلاتين",
    "EK":    "Heart Warmer",
    "EL":    "Air/oxygen Mixer",
    "EM":    "Thermalator",
    "EN":    "Catheter Lab",
    "EO":    "Pipet",
    "EP":    "Lab Refrigerator",
    "EQ":    "Urine Analyzer",
    "ER":    "O2 Analyzer",
    "ES":    "Monitor",
    "ET":    "Tissue processor",
    "EU":    "Oven",
    "EV":    "Blood mixer",
    "EW":    "Invasive Blood Pressure",
    "EX":    "جهاز كمادات Hot pack",
    "EY":    "Freezer",
    "EZ":    "Non-invasive hemodynamic monitor",
    "FA":    "Elisa Washer",
    "FB":    "Respiratory aid system",
    "FC":    "High Flow Nasal Cannula",
    "FD":    "جهاز تحليل المخدرات Drugs analyzer",
    "FE":    "Nebulizer",
    "FF":    "EEG",
    "FG":    "ACT نسبة التجلط",
    "FH":    "Electromagnetic waves",
    "FI":    "Hormones Analyzer",
    "FJ":    "Operating table",
    "FK":    "Air compressor",
    "FL":    "PCR Cube",
    "FM":    "PCR Rotor",
    "FN":    "Ophthalmology Diathermy كي شعرة",
    "FO":    "جهاز قياس نسبة الهيموجلوبين فى الدم Hemoglobin",
    "FP":    "Dexa scan",
    "FQ":    "c-pap",
    "FR":    "Sodium & pot. analyser",
    "FS":    "جهاز قياس نسبة الكلور فى المياه",
    "FT":    "التغذية الراجعة",
    "FU":    "تحريك مفاصل",
    "FV":    "Cardiac enzyme",
    "FW":    "Blood culture system",
    "FX":    "Water distillation",
    "FY":    "Peritoneal Dialysis",
    "FZ":    "Endoscope",  # master says: ENT UNIT
    "GA":    "Bilirubin meter",
    "GB":    "Hygrometer",
    "GC":    "Portable Data Logger",
    "GD":    "Protein analyzer",
    "GE":    "Temperature calibration tester",
    "GG":    "ESR-جهاز ترسيب",
    "GF":    "Pulse Oximetery Simulator",
    "VAH":   "Vital sign (SPO2)",
    "VCB":   "Vital sign (NIBP)",
    "GH":    "Bipap",
    "GI":    "Bactrial identification device",
    "GJ":    "Aortic balloon",
    "GK":    "Tourniquet",
    "GL":    "DNA/RNA Extractor",
    "GM":    "Corona virus Analyzer",
}


def name_for(code: str) -> str | None:
    """The device this code names, or None when the list does not have it."""
    return DEVICE_NAMES.get(code.strip().upper())
